version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports: 
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  backend:
    image: backend
    container_name: backend_app
    depends_on: 
      - "mongodb"
    ports: 
      - "4000:4000"
    env_file:
      - .env
volumes:
  mongodb_data:
