name: CI
on:
  pull_request:
    branch:
      - master
      - main 

job:      
  build:
    name: Project build
    runs-on: ubuntu-latest
    step:
      - uses: action/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Installing Dependencies    
      - run: npm ci
      - name: Start Building
      - run: npm run build 
  

      

# name: Node.js CI

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4
#       - name: Use Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20.x'
#       - run: npm ci
#       - run: npm run build --if-present
#       - run: npm test